apiVersion: v1
kind: SopsSecret
metadata:
    name: sops-harbor-xsrf
    namespace: sops-harbor
type: Opaque
stringData:
    CSRF_KEY: ENC[AES256_GCM,data:etkHmrqrKOwN/qgkopzmd/R4O9ZltXI27X008CY1bMM=,iv:LAwK+f3cechy9Op+pKlmD/GLb4vvkbOzsabqJXzHNfc=,tag:dmmv+PEJwTjNwsLhdvipyg==,type:str]
sops:
    age:
        - recipient: age1rqgkdz06pmtrwax6ttykfc3macheykuk4vnpyrxxhw8qdgssk3jqma2tvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbHZPZzduSFA5Y0gxTTRZ
            YWNKOWIyUURWTEpVRStEOXlKM25RdjJhc25RCk9kMzlLNEk5cjlNY1lOWnBrc3hm
            SERZSXFBR3dNVVNaMmc5NFIwYkQ1VUkKLS0tIGVqVjIyMjhSR2dOYXRVMnpqTy8x
            UGduL1ZmM3hzZVRpejJ3NWUzMEt4SGcKL7nRHzzEwJCiCZ8/KKpZlHqW9uG1NH9g
            7tWKpfsQVRf+obsqQT0cFyLdBSwyERvBP/5mg2UEB73Un73tUeexeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T14:28:27Z"
    mac: ENC[AES256_GCM,data:Xq6g0NBXSb9vvF9dxZboHjjozPaNkxYpzNyAXnrEz7O04eJJSWmfytUnRvrkn3t9pdTKdtnu/9pF3BxN7fpVAL39YOe+AUBayZmWQ4NPmBo4/H/CGQRWEVtLrj1lbtoG5VXG51E2/nIsT0YBmUQkEMLZ9fxyGquiECBHUviyRwE=,iv:nfc5P+/0F0xiB75KVPhkxly6PRmh/7eh52XwUOuEZxk=,tag:4g9E3Oib/BaGlIEzz6ku+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
