apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sops-harbor
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: sops-harbor
  project: default
  sources:
    - chart: harbor
      helm:
        valuesObject:
          core:
            extraEnvVars:
              - name: CONFIG_OVERWRITE_JSON
                # Note: Replaced value with valueFrom.
                valueFrom:
                  secretKeyRef:
                    name: sops-harbor-config # name of your already created secret
                    key: CONFIG_OVERWRITE_JSON
            # Note: Replaced secret with existingSecret. "If using existingSecret, the key must be secret."
            existingSecret: "sops-harbor-core2"
            secretName: harbor-token-tls
            existingXsrfSecret: sops-harbor-xsrf
            existingXsrfSecretKey: CSRF_KEY
            # Note: Replaced xsrfKey with existingXsrfSecret and existingXsrfSecretKey.
          expose:
            ingress:
              className: nginx
              hosts:
                core: sops-harbor.orlandotorres.dev
            tls:
              certSource: none
              enabled: true
            type: ingress
          externalURL: https://sops-harbor.orlandotorres.dev
          # Note: Replaced harborAdminPassword with existingSecretAdminPassword and existingSecretAdminPasswordKey.
          existingSecretAdminPassword: "sops-harbor-admin-password"
          existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
          internalTLS:
            enabled: false
          jobservice:
            # Note: Replaced secret with existingSecret and existingSecretKey.
            existingSecret: sops-harbor-jobservice2
            existingSecretKey: JOBSERVICE_SECRET
          persistence:
            imageChartStorage:
              disableredirect: true
              s3:
                bucket: registry
                existingSecret: minio-creds
                region: us-east-1
                regionendpoint: s3.orlandotorres.dev
                secure: true
                skipverify: true
              type: s3
          registry:
            credentials:
              # Note: Replaced htpasswdString with existingSecret.
              existingSecret: sops-harbor-credentials
            secret: U5P8BVEwsJVArMlz
      repoURL: https://helm.goharbor.io
      targetRevision: 1.15.1
    - path: harbor
      repoURL: https://github.com/johnasbaghi/sops-keycloak
      targetRevision: HEAD
    - path: secrets/harbor
      repoURL: https://github.com/johnasbaghi/sops-keycloak
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
      - CreateNamespace=true
