apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: keycloak
spec:
  destination:
    name: in-cluster
    namespace: keycloak
  project: default
  source:
    path: keycloak
    repoURL: https://github.com/DevalexLLC/argocd-cluster-test
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
