apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sops-keycloak-operator
spec:
  destination:
    name: in-cluster
    namespace: sops-keycloak
  project: default
  source:
    path: keycloak-operator
    repoURL: https://github.com/DevalexLLC/sops-keycloak
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        linkerd.io/inject: enabled
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
      - CreateNamespace=true
