kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sops-minio-operator
spec:
  destination:
    name: in-cluster
    namespace: sops-minio-operator
  project: default
  source:
    chart: operator
    repoURL: https://operator.min.io
    targetRevision: 6.0.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
      - CreateNamespace=true
