apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-token-ca
spec:
  commonName: harbor-token-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ca-issuer
  secretName: harbor-token-tls
