apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: vault-unseal
spec:
  entrypoint: main
  imagePullSecrets: []
  templates:
    - name: main
      steps:
        - - name: get-replicas
            template: get-replicas
        - - arguments:
              parameters:
                - name: replica
                  value: '{{item}}'
            name: configure
            template: configure
            withSequence:
              count: '{{steps.get-replicas.outputs.parameters.replicas}}'
    - name: get-replicas
      outputs:
        parameters:
          - name: replicas
            valueFrom:
              jsonPath: '{.spec.replicas}'
      resource:
        action: get
        manifest: |
          apiVersion: apps/v1
          kind: StatefulSet
          metadata:
            name: vault
    - container:
        args:
          - echo "Unsealing replica {{inputs.parameters.replica}}"; vault operator unseal $VAULT_KEY
        command:
          - sh
          - -c
        env:
          - name: VAULT_ADDR
            value: https://vault-{{inputs.parameters.replica}}.vault-internal:8200
          - name: VAULT_CACERT
            value: /certs/ca-bundle.pem
          - name: VAULT_KEY
            valueFrom:
              secretKeyRef:
                key: unseal_key
                name: vault-initial-secret
        image: hashicorp/vault:1.14.2
        name: main
        volumeMounts:
          - mountPath: /certs/ca-bundle.pem
            name: ca-bundle
            subPath: ca-bundle.pem
      inputs:
        parameters:
          - name: replica
      name: configure
      retryStrategy:
        backoff:
          duration: 1s
          factor: "2"
          maxDuration: 30s
        limit: "10"
      volumes:
        - configMap:
            name: ca-bundle
          name: ca-bundle
