apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
spec:
  commonName: system:node:*.svc.cluster.local
  dnsNames:
    - '*.vault-internal'
    - '*.vault-internal.svc.cluster.local'
    - '*.vault-internal.default.svc.cluster.local'
    - '*.default'
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-issuer
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  secretName: tls-server
  subject:
    organizations:
      - system:nodes
  usages:
    - digital signature
    - key encipherment
    - data encipherment
    - server auth
    - client auth
